### ISSUE TITLE
Recent update breaks the build/old flow

### ISSUE THREAD

**Issue by simonebogni** [OlegGulevskyy/zendesk-vite-boilerplate#15]
Hi, I've started using this boilerplate for a Zendesk project.
It looks really promising and I really wanted to integrate it in our app development process.
However, I've noticed that the update from 3 days ago introduced significant changes.
As a result, the way to create a regular app (e.g. in the ticket sidebar) is different and the docs and scripts have not been updated.
Unfortunately this makes the boilerplate unusable at the moment - at least from what I've seen.

The repository is also using 3 different package managers (npm, yarn and pnpm), but the scripts expect you to run yarn.
Package-lock.json (for npm) is not updated, compared to the other 2 files.
I suggest one of the following options:
- give the option to developers to choose what tool they want. That means keeping all the lock files updated and either updating the script to accept the name of the package manager as a parameter, or have a section in the docs that explain how and where to make the change in the scripts
- stick to only yarn

I imagine it's still a work in progress, but please consider doing these changes on feature branches and not on the main branch.
In the same major version, changes should be backward compatible.
The lack of releases or tags on this repo makes it also very hard to clone an old stable version.
Thank you :)

**Comment by OlegGulevskyy** [comment]
Hey @simonebogni , thanks for detailed issue! You are right, my bad :) It's my pretty much only OSS repo that I maintain and I haven't thought of this. I knew the changes were breaking but I didn't rush to clean up and explain this in the repository's README. Frankly I didn't think much people using it nowadays 👀 
Sorry for the inconvenience!

I will clean up the repository today with updated README

**Comment by simonebogni** [comment]
@OlegGulevskyy Thank you, Oleg. I have to say that I really appreciate your fast response. I wasn't expecting to get a reply that fast! 😄
And now that I reread it, I hope I didn't come off bad in my previous comment 😅
I simply meant it as a list of things that could be fixed

**Comment by OlegGulevskyy** [comment]
No worries at all! Thanks for taking your time to write it in such details, nothing was taken badly, quite the opposite
I said I would do this thing yesterday, but I haven't had time to finish it, as I am preparing a big update to the project's documentation. The branch `clean-up` already exists and works well, I am building my own apps based on it, but.. Readme will be removed very soon and instead this project will have a step by step guides, with configuration details, behaviour explanation and this all will be hosted on a different platform (`gitbook`), because I hate writing .md :D 
I am hoping this will be done today.

In case you need to start running with this asap, feel free to ping me in [Discord server](https://discord.gg/KtYVu3n3db)
